app:
    resource: "@AppBundle/Controller/"
    type:     annotation

tralang:
    resource: "@TralangBundle/Controller"
    type:     annotation
registration:
    path:     /register
    defaults: { _controller: TralangBundle:Registration:register }

