app:
    resource: "@AppBundle/Controller/"
    type:     annotation

tralang:
    resource: "@TralangBundle/Controller"
    type:     annotation
registration:
    path:     /register
    defaults: { _controller: TralangBundle:Registration:register }
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
