# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      admin.users:
            class: TralangBundle\Admin\UserAdmin
            arguments: [~, TralangBundle\Entity\User, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: User }
      admin.words:
            class: TralangBundle\Admin\WordsAdmin
            arguments: [~, TralangBundle\Entity\Words, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Words }

      admin.categories:
            class: TralangBundle\Admin\CategoriesAdmin
            arguments: [~, TralangBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Categories }
